[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
port=8501
headless=true # This will eliminate automatically open browser[browser] # This ip and port will show in command prompt

[browser] # This ip and port will show in command prompt
serverAddress = "allmithal.ca" # Put your Local IP or Domain Name
serverPort = 8501